# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheqDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheqDemo
  pod 'Charts', '~> 3.3'
  pod 'NavigationDropdownMenu'
  pod 'Hex'
  pod 'SwiftSpinner'
  
  target 'CheqDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTest'
  end
end
