# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheqDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheqDemo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire' 

  target 'CheqDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
    pod 'SnapshotTest'
  end
end
